[package]
name = "sample-plugin"
version = "0.1.0"
edition = "2021"

[lib]
name = "sample_plugin"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.37.0", default-features = false }
pyo3 = { version = "0.20.0", features = ["extension-module", "abi3-py38"] }
pyo3-polars = { version = "0.11.1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
